name: CI

on: push

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-java@v1
          with:
            java-version: '8'
      -   name: Build all code
          id: gradle
          uses: eskatos/gradle-command-action@v1
          with:
            arguments: assemble --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
          env:
            CI: true
      -   name: Attach build scan to commit
          if: ${{ always() }}
          shell: bash
          run: |
            curl \
            --silent \
            --show-error \
            --fail \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{
                    "state":"${{ steps.gradle.outcome }}",
                    "target_url": "${{ steps.gradle.outputs.build-scan-url }}",
                    "context": "SCAN / assemble"
                }'
  check:
    needs: assemble
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        java: [8, 9, 10, 11, 12, 13, 14-ea]
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
      -   name: Run all tests
          id: gradle
          uses: eskatos/gradle-command-action@v1
          with:
            arguments: check --scan --continue --no-daemon "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}"
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
          env:
            CI: true
      -   name: Attach build scan to commit
          if: ${{ always() }}
          shell: bash
          run: |
            curl \
            --silent \
            --show-error \
            --fail \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{
                    "state":"${{ steps.gradle.outcome }}",
                    "target_url": "${{ steps.gradle.outputs.build-scan-url }}",
                    "context": "SCAN / ${{ runner.os }} (Java ${{ matrix.java }})"
                }'
