name: CI

on: push

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-java@v1
          with:
            java-version: '8'
      -   name: Build all code
          id: gradle
          uses: eskatos/gradle-command-action@v1
          with:
            arguments: assemble --scan --continue "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}" -PbintrayUsername=dummy -PbintrayPassword=dummy
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
  check:
    needs: assemble
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        java: [8, 9, 10, 11, 12, 13]
    steps:
      -   uses: actions/checkout@v2
      -   uses: actions/setup-java@v1
          with:
            java-version: ${{ matrix.java }}
      -   name: Run all tests
          id: gradle
          uses: eskatos/gradle-command-action@v1
          with:
            arguments: check --scan --continue "-Ddev.nokee.gradle.cache.remote.username=${{ secrets.GRADLE_CACHE_USERNAME }}" "-Ddev.nokee.gradle.cache.remote.password=${{ secrets.GRADLE_CACHE_PASSWORD }}" -PbintrayUsername=dummy -PbintrayPassword=dummy
            wrapper-cache-enabled: true
            dependencies-cache-enabled: true
